FROM golang:1.15.2 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.12.0

COPY --from=builder /app/victron-mqtt-statsd /bin/victron-mqtt-statsd

CMD ["/bin/victron-mqtt-statsd"]